version: 0.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: dotnet restore ./src/Akkatecture/Akkatecture.csproj
- cmd: dotnet restore ./src/Akkatecture.Clustering/Akkatecture.Clustering.csproj
- cmd: dotnet build ./src/Akkatecture/Akkatecture.csproj -c Release
- cmd: dotnet build ./src/Akkatecture.Clustering/Akkatecture.Clustering.csproj -c Release
- cmd: dotnet pack ./src/Akkatecture/Akkatecture.csproj --output packageoutput/akkatecture --verbosity d
- cmd: dotnet pack ./src/Akkatecture.Clustering/Akkatecture.Clustering.csproj --output packageoutput/akkatectureclustering --verbosity d
test_script:
- cmd: dotnet test ./test/Akkatecture.Tests/Akkatecture.Tests.csproj
deploy:
- provider: NuGet
  api_key:
    secure: jNtt/O0YdM+cKFiPbqv5EXIgbXlvGzXR45WLJdEWdhIwKTUCoGr44lmUkVY9xigd
  on:
    branch: master
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: v$(appveyor_build_version)
  auth_token:
    secure: dgHvp6cRuN111wnt2rANR25qfklalE+m06hxhy7XbFRkoGjW46h9mu8wxqsaTPHj
  artifact: /.*\.nupkg/ 
  prerelease: true
  on:
    branch: master